# Generated by Django 4.2.1 on 2023-05-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_cargo_created_at_cargo_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='pickup_location',
            new_name='pickup',
        ),
    ]
