# Generated by Django 4.2.1 on 2023-05-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_rename_pickup_location_cargo_pickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='delivery_location',
            new_name='delivery',
        ),
    ]
